### ISSUE TITLE
ログアウト処理を作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#100]
# Doneの定義
- ログアウトAPIとフロントエンドが通信できていること
- ローカルストレージからログインセッションが削除されていること

**Comment by kobayashi-m42** [comment]
ストーリーポイントは5を想定

**Comment by keitakn** [comment]
@kobayashi-m42 うん！これも5くらいは必要だと思う🐱！
