### ISSUE TITLE
カテゴリ追加時のバリデーション処理を追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#103]
# Doneの定義
- バリデーションエラーの場合、エラーメッセージが表示されること

**Comment by kobayashi-m42** [comment]
ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 issueが `qiita-stocker-frontend` に含まれてたから、フロントエンド側のValidationって事で良いかな🐱？

もしそうなら2で良いと思う！厳密にやる必要はなくて、最終的にはAPI側でもValidationするだろうから、空文字列かどうかを見るくらいで良いと思う！

**Comment by kobayashi-m42** [comment]
フロントのバリデーション処理って意味だったよ！
> 空文字列かどうかを見るくらいで良いと思う！
了解！2でポイントつけておくね！
