### ISSUE TITLE
interfaceの定義を見直す

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#112]
# Doneの定義
 - Interfaceが適切なファイルに定義されていること

# 補足情報
interfaceが以下に定義されており、ファイル名と定義内容が一致していないので修正する。
- `domein/Qiita.ts`
-  `types/login.ts`

**Comment by kobayashi-m42** [comment]
ストーリーポイントは1を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！1で問題ないと思う🐱！
