### ISSUE TITLE
利用規約画面を作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#121]
# Doneの定義
- 利用規約画面が作成されていること

# 補足情報
利用規約の内容については、別のIssueで作成する。
このIssueは、単純に画面を作成するのみ。

**Comment by kobayashi-m42** [comment]
ストーリーポイントは、ただ画面を表示するだけだから2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で問題なさそうだね🐱
