### ISSUE TITLE
AWS上のAPIに接続できるように環境変数を変更する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#125]
# Doneの定義
- フロントエンドからAWSのAPIに接続できること

# 補足
環境変数を修正して、S3にデプロイする。

**Comment by kobayashi-m42** [comment]
ストーリーポイントは、1を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 1で問題ないと思う🐱！
ただAWS上で予期しない問題が起きる可能性があるから、その場合は別のissue立てて対応するのが良いかな！

**Comment by kobayashi-m42** [comment]
やったこと
- `.env`のVUE_APP_API_URL_BASEを修正
- qiita-stocker-backendの`.env`のCORS_ORIGINについても、ドメインを修正

フロントアプリケーションからバックエンドのAPIに接続できることを確認
