### ISSUE TITLE
ストック同期中のメッセージを表示する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#135]
# Doneの定義
- ストック同期中にローディングメッセージが表示されること

# 補足情報
仕様変更により、ストックの同期処理はなくなったので、ストック取得中のメッセージを表示する。

**Comment by kobayashi-m42** [comment]
ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で大丈夫だと思う🐱！
