### ISSUE TITLE
Qiitaの認可サーバへリクエストし認可コードを取得する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-frontend#14]
# Doneの定義
- Qiita側にクライアントアプリが登録されている事
- Qiita側にリダイレクトURIを始めとする必要な情報が登録されている事
- Qiita側から認可コードが取得出来ている事
- 取得した認可コードが画面に表示されている事

# 補足
認可コードを画面に表示させる処理は本当に一時的な物なので適当な実装で良い。

## 参考
- https://qiita.com/SoraKumo/items/95bc5ed543e195cc2f7f

**Comment by keitakn** [comment]
@kobayashi-m42 
ストーリーポイントは5か8かな、色々調査が必要なところもあるから8が無難かも🐱

**Comment by kobayashi-m42** [comment]
@keitakn 
ストーリーポイントは8にするね！
