### ISSUE TITLE
自然時間経過でログインセッションが無効になった場合メニュー画面は切り替わらない？

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-frontend#150]
# 概要
- 表題の通り

# 再現手順
1. 通常の手順でログインを行う
2. ログインセッションの有効期限が切れるまで待つ
3. ログインが必要なページ（ストック一覧等）に遷移する

ログインが必要な状態になるがメニューがログイン状態のままでログインボタンが表示されない

# 再現環境
- GoogleChromeの最新版

# このバグによって引き起こされる問題
ログインセッションが切れたユーザーが再ログイン出来ない（ローカルストレージを自分でクリアすれば可能）

# 補足情報
ログインセッション有効期限切れのerrorになった場合、ローカルストレージから有効期限が切れたログインセッションを削除するようにすればイケると思う🐱！

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは3とかかな🐱？

**Comment by kobayashi-m42** [comment]
うん！3にするね！🐱
