### ISSUE TITLE
カテゴライズ済みのストックを表示するコンポーネントを作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#153]
# Doneの定義
- カテゴライズ済みのストックを表示するコンポーネントが作成されていること
- カテゴリ一覧で選択中のカテゴリは、カテゴライズ時に選択できないこと

# 補足情報
-  `CategorizedStockList`、`CategorizedStock`コンポーネントを作成する
- カテゴリ一覧で選択中のカテゴリは、カテゴライズ時に選択できないように修正する

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で問題なさそうだね🐱！
