### ISSUE TITLE
公式ツイッターへのリンクをフッターに追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#164]
# Doneの定義
- フッターにリンクが追加されていること

**Comment by keitakn** [comment]
@kobayashi-m42 とりあえず作ったよ🐱（認証情報はGoogleドライブに入れておいた）

https://twitter.com/mindexer_org

プロフィール画像とか説明はサービスのロゴが出来たら追加しようと思う！

**Comment by kobayashi-m42** [comment]
@keitakn 
作成ありがとう！このアカウントでフッター作成するね！🐱
