### ISSUE TITLE
アカウント登録画面に利用規約への同意チェックボックスを追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#177]
# Doneの定義
- 表題の件が実施されている事

# 補足
Qiitaアカウントの連携についての説明事項を追加する予定

**Comment by kobayashi-m42** [comment]
@keitakn ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で大丈夫だと思う🐱
