### ISSUE TITLE
SEO対策を実施する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#186]
# Doneの定義
- SEO対策を実施する

# 補足情報
https://support.google.com/webmasters/answer/7451184?hl=ja

**Comment by keitakn** [comment]
@kobayashi-m42 また参考になりそうな記事見つけたから共有するね🐱

https://note.mu/hozmii/n/n0ee269097462

サーチコンソールとかGoogle Analyticsとかは別課題のほうが良いかもね、それなりに時間かかりそうだし、SPAの場合は↓な感じでちょっと実装方法を工夫する必要がありそう！

https://qiita.com/tiwu_official/items/eeaa1424ca757362e836

この課題の範囲としては、metaタグのDescriptionとかKeywordを考えて配置するくらいかな・・・

**Comment by kobayashi-m42** [comment]
@keitakn 
リンク貼ってくれてありがとう！すごく参考になった🐱
> この課題の範囲としては、metaタグのDescriptionとかKeywordを考えて配置するくらいかな・・・

うん！サーチコンソールとかGoogle Analyticsは別途対応して、この課題では最低限必要なことのみ対応するね！
