### ISSUE TITLE
デプロイスクリプトで index.prod.html, index.stg.html をアップロードしないように対応する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-frontend#194]
# Doneの定義
- 表題の件に従いデプロイスクリプトが改修されていること

# 補足情報
大きな問題はないがほぼ同じ内容のhtmlファイルが複数デプロイされてしまうのでSEOに悪影響を及ぼす可能性がある。

リリースまでに必須ではないが、対応しておくと望ましい。（最悪、デプロイ後に余計なファイルを手動で消すという運用でカバー出来なくはない為）

**Comment by kobayashi-m42** [comment]
@keitakn 
なるほど！必要のないファイルまでアップロードされてしまってるんだね！
ストーリーポイントは2でいいと思う！🐱
