### ISSUE TITLE
カテゴライズ解除ボタンのUIを改善する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#195]
# Doneの定義
- スマホでカテゴライズ解除ボタンを間違えて押下しないようなUIに変更されていること

# 補足情報
スマホでストック一覧を表示すると、間違えてカテゴライズ解除ボタン([×]ボタン)を押下してしまうので、UIを改善する。
改善案としては、「カテゴリに分類する」ボタンの隣に「カテゴライズを解除する」ボタンを表示し、ボタンが押下された場合のみ[×]ボタンを表示する。

**Comment by kobayashi-m42** [comment]
@keitakn ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！実装案も考慮して2で大丈夫だと思う🐱！
