### ISSUE TITLE
developブランチを作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#198]
# Doneの定義
表題の件が実施されていること

**Comment by kobayashi-m42** [comment]
@keitakn 下記の通りdevelopブランチを作成したよ！🐱
https://github.com/nekochans/qiita-stocker-frontend/branches

**Comment by keitakn** [comment]
@kobayashi-m42 ありがとう🐱！このissueはクローズするね👌
