### ISSUE TITLE
プライバシーポリシーにCookieを使用していることを追記する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#201]
# Doneの定義
表題の件が満たされていること

# 補足情報
[Google アナリティクス利用規約](https://www.google.co.jp/analytics/terms/jp.html)の7条に対応するため
> お客様はプライバシー ポリシーを公開し、そのプライバシー ポリシーで、お客様がデータ収集のために Cookie を使用していることを必ず通知するものとします。

**Comment by kobayashi-m42** [comment]
ストーリーポイントは、2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で大丈夫だと思う🐱
