### ISSUE TITLE
Circle CI 上でnot enough memoryが起こる現象を解消する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-frontend#219]
# Doneの定義
- 表題の件が解消されていること

# 補足情報
https://github.com/nekochans/qiita-stocker-frontend/pull/218 でCIがエラーを返してきたので対応。

以下の記事のように 実行時に `--runInband` を渡す方法で行けそう。

https://qiita.com/takewell/items/7b7731ffbfcbc5403efd

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは念の為、3でいこうと思っている🐱

**Comment by kobayashi-m42** [comment]
@keitakn 
デプロイありがとう！ローカルでは発生しない問題なんだね・・
ポイントは3でいいと思う！🐱
