### ISSUE TITLE
ログイン判定に使っているCookieの有効期限を延長する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-frontend#234]
# Doneの定義
- 一度ログインを行ったらしばらくログイン状態を維持出来るようになっている事

 # 補足情報
今はブラウザを閉じるとログイン状態が切れてしまうので、ある程度は持続させるようにCookieに有効期限を付ける。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは2を想定しているよ🐱！

**Comment by kobayashi-m42** [comment]
@keitakn 確認が遅くなってごめん🙏ポイントは2で大丈夫だと思う！
