### ISSUE TITLE
コールドスタート対策の手法をProvisioned Concurrencyを使った手法に変更する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-frontend#235]
# Doneの定義
- `serverless-plugin-warmup` が削除され、 `Provisioned Concurrency` が設定されている事

 # 補足情報
既に対応されているっぽいので、設定を書き換えてデプロイするだけで終わりそう。

https://serverless.com/blog/aws-lambda-provisioned-concurrency/

serverless自体は最新に更新しておく必要がありそう。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは2で大丈夫だと思ってるよ🐱！

**Comment by kobayashi-m42** [comment]
@keitakn うん！2で大丈夫そうだね🐱
