### ISSUE TITLE
window.localStorageへアクセスしている部分を別の関数に移動する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#37]
# Doneの定義
- window.localStorageへアクセスしている部分が別の関数に切り出されていること

**Comment by keitakn** [comment]
これは結構難しそう、関数を作る事自体は簡単だけど、設計考えるとなると5くらいは見ておいたほうが無難かも🐱！

**Comment by kobayashi-m42** [comment]
なるほど！3でいけるかなと思ったけど、設計も入るから5の方が良さそうだね！
