### ISSUE TITLE
セッションIDを永続化する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#45]
# Doneの定義
- セッションIDが永続化されていること

**Comment by keitakn** [comment]
@kobayashi-m42 
一番簡単なのはローカルストレージを使う事かな！
理想としては https://github.com/nekochans/qiita-stocker-frontend/issues/37 が終わってから着手すればこの課題は2くらいのストーリーポイントで処理出来そうとだと思う🐱！
