### ISSUE TITLE
components配下のコンポーネントをpagesに移動する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#52]
# Doneの定義
- components配下のコンポーネントがpagesに移動していること

# 補足情報
`pages/`のコンポーネントをVue-Routerのルーティングに対応するページのファイルをとする。
現状だと、`components/`のコンポーネントがそれに該当している。

**Comment by kobayashi-m42** [comment]
ストーリーポイントは、1を想定！

**Comment by keitakn** [comment]
@kobayashi-m42 うん！ただ移動するだけなら1で問題ないと思う👌
