### ISSUE TITLE
HeaderコンポーネントのURLを外から渡す

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#73]
# Doneの定義
- HeaderコンポーネントのURLが外から渡されて設定されていること

**Comment by kobayashi-m42** [comment]
ストーリーポイントはテストも考慮すると2を想定🐱

**Comment by keitakn** [comment]
うん！2で問題ないと思う！🐱

**Comment by kobayashi-m42** [comment]
@keitakn 
URLを指定するのではなく、ルートパスを指定するように修正済みだから、このIssueはストーリーポイントを削除してクローズしてしまって問題ないかな？🐱
https://github.com/nekochans/qiita-stocker-frontend/commit/c24b9e6220c2a071facc0cfd96fea26863bdd91a#diff-b3f8a7afecce4b53147a2f9679f46d7a

**Comment by keitakn** [comment]
@kobayashi-m42 うん！問題ないと思う🐱
