### ISSUE TITLE
ログイン状態によってHeaderの表示を切り替える

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#74]
# Doneの定義
- ログイン状態によってHeaderの表示が切り替わること

# 補足情報
- 現状だと、常にログアウトが表示されている
- このIssueの前にログイン状態をstateに持たせる必要がある

**Comment by kobayashi-m42** [comment]
ストーリーポイントは、3を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で問題ないと思う🐱！
