### ISSUE TITLE
アカウントページのスタイリング

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#78]
# Doneの定義
- アカウントページにCSSが当てられている事

# 補足情報
メインのStockの機能が確定していないので、仮の画面を作成する。

**Comment by kobayashi-m42** [comment]
Stockの仕様にも絡む画面になるから、ストーリーポイントは5を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 
>Stockの仕様にも絡む画面になるから、ストーリーポイントは5を想定🐱

うん！問題ないと思う🐱！

https://github.com/nekochans/nekochans/issues/21 が終わらないと、ここは確定出来ないからね・・
