### ISSUE TITLE
MediaListコンポーネントにpropで記事の一覧を渡して表示する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#82]
# Doneの定義
- propで受け取った記事の一覧が表示されていること
- 記事が存在しなかった場合のメッセージが表示されていること

# 補足情報
- ログイン後のページのスタイリングを進めるためのIssue
- 記事一覧のデータは、仮の値を用意する

**Comment by kobayashi-m42** [comment]
ストーリーポイントは3を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！3で良いと思う🐱！
