### ISSUE TITLE
SideMenuListコンポーネントにpropでカテゴリの一覧を渡して表示する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#83]
# Doneの定義
-  propで受け取ったカテゴリの一覧が表示されていること

# 補足情報
- ログイン後のページのスタイリングを進めるためのIssue
- カテゴリ一覧のデータは、仮の値を用意する

**Comment by kobayashi-m42** [comment]
ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で良いと思う🐱！
