### ISSUE TITLE
カテゴリの登録のUI設計

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#85]
# Doneの定義
- カテゴリ登録ページが作成されていること

# 補足情報
Stockの仕様が未確定のため、暫定の画面イメージを作成する

**Comment by kobayashi-m42** [comment]
ストーリーポイントは、5を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん、結構考える事あるから5は必要だね🐱！

**Comment by keitakn** [comment]
@kobayashi-m42 今日話して決まった事書いておくね🐱

- ユーザーが持つStockは https://github.com/nekochans/qiita-stocker-backend/issues/55 で取得するAPIで取得する（可能な限りバックエンド側で必要なデータを返す）
- Stockされた記事は最初は「未分類」として扱う（ラベルが未選択の場合はQiita APIを使ってStockされた記事一覧を取得する）
- 自身が作成したラベルをクリックすると対象のラベルに紐付いた記事一覧が取得される

https://github.com/nekochans/nekochans/issues/21 は完了にする

**Comment by kobayashi-m42** [comment]
まとめてくれてありがとう！🐱
