### ISSUE TITLE
Actionの非同期テストを実装する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-frontend#9]
# Doneの定義
- 天気APIからデータを取得するActionのテストが実装されていること

**Comment by keitakn** [comment]
# memo

本件は https://github.com/nekochans/qiita-stocker-frontend/pull/8 で実施して上手くいかなっかた件。

実装方法を調査して実施する。

**Comment by keitakn** [comment]
>WeatherModule.state が意図した通りに変わっている事

良く考えたら `const commit = jest.fn();` している時点で `mutations.saveWeather` は呼ばれない。。。

ここは `commit.mock.calls` を除いて確かに commit() が 'saveWeather' と mockで指定した値を引数に呼ばれているのを確認するのが限界だと思われる。

一見 axios をmockした事によりランダムなAPIの返り値を固定化出来ているのでテストが常に成功するハズだ。
