### ISSUE TITLE
SPAアプリケーションを任意のドメイン名で接続出来るようにする

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-frontend#90]
# Doneの定義
- 表題の件が実施されている事

# 補足情報
ここで取得するドメイン名は仮。

- https://qiita.com/keitakn/items/35ae8cc56f5c0a4766b4
- https://qiita.com/keitakn/items/4b2db95eae81044a779c

以下のようになると分かりやすい🐱

（例）ドメイン `nekochans.net` を購入した場合

- https://www.nekochans.net がフロントエンドのURL
- https://api.nekochans.net がフロントエンドのURL

サブドメインは環境変数毎に付けると分かりやすい↓

## フロントエンド
https://www.nekochans.net（本番）
https://stg-www.nekochans.net（ステージング）
https://dev-www.nekochans.net（開発）

## バックエンド
https://api.nekochans.net（本番）
https://stg-api.nekochans.net（ステージング）
https://dev-api.nekochans.net（開発）

**Comment by kobayashi-m42** [comment]
やったこと
- Route 53でドメインの登録とサブドメインの設定
- Certificate Managerで証明書を作成
- CloudFrontの`Alternate Domain Names`にサブドメインを指定し、`SSL Certificate`に発行した証明書を設定
